### ISSUE TITLE
Add service principal login tests to this project's build

### ISSUE THREAD

**Issue by lokst** [CircleCI-Public/azure-aks-orb#5]
Currently the suite of tests are done with a user login as the project's configured environment variables include the `AZURE_USERNAME` environment variable, causing a user login to be performed. It would be good to have tests that use a service principal login to increase the orb's automated test coverage.

Here is an example of how the orb can be currently tested with a service principal login in a separate project, assuming `AZURE_SP`, `AZURE_SP_PASSWORD` and `AZURE_SP_TENANT` are configured as project environment variables and `AZURE_USERNAME` is not. The `az aks create` command will be run with the `--service-principal` and `--client-secret` arguments based on the above-mentioned environment variable configuration as `AZURE_SP` and `AZURE_SP_PASSWORD` are the default environment variable names used for the `service-principal` and `client-secret` parameters of the `create-cluster` job.

Also note that the `delete-service-principal` parameter of the `delete-cluster` job needs to be set to `false` if the service principal used for the login will not have the permissions necessary to delete the service principal created for the cluster. See: https://serverfault.com/questions/889976/how-to-give-azure-service-principal-the-same-rights-as-my-own-user

```
version: 2.1

orbs:
  azure-aks: circleci/azure-aks@0.2.0

workflows:
  deployment:
    jobs:
      - azure-aks/create-cluster:
          cluster-name: aks-sp-deployment
          resource-group: aks-sp-deployment-rg
          create-resource-group: true
          location: eastus
          generate-ssh-keys: true
      - azure-aks/delete-cluster:
          cluster-name: aks-sp-deployment
          resource-group: aks-sp-deployment-rg
          delete-service-principal: false
          delete-resource-group: true
          requires:
            - azure-aks/create-cluster
```
